---
- name: "NIM operations to define, display and remove resource objects"
  hosts: nim1
  remote_user: root
  gather_facts: no
  vars:

    alloc_resource_v:       lpp_source_test4
    spot_name_v:            spot_test4
    spot_final_location_v:  /nim1/spot_test4_from_lpp_source
    lpp_source_v:           lpp_source_test4
    software_lpp_source:    /nim1/lpp_source
    lpp_source_location:    /nim1/lpp_source_test4


  collections:
  - ibm.power_aix
  tasks:

# Setup

    - name: Setup- Remove the spot resource.
      ibm.power_aix.nim_resource:
        action: absent
        name: "{{ spot_name_v }}"
      register: result
    - debug: var=result

    - name: Setup- Remove the lpp_source.
      ibm.power_aix.nim_resource:
        action: absent
        name: "{{ lpp_source_v }}"
      register: result
    - debug: var=result

# Tests. Expected functions.

    - name: Create/define an lpp_source NIM resource object from the 
            software in the system.
      ibm.power_aix.nim_resource:
        action: present
        name: "{{ lpp_source_v }}"
        object_type: lpp_source
        attributes:
          source: "{{ software_lpp_source }}"
          location: "{{ lpp_source_location}}"
      register: result
    - debug: var=result

    - name: Create/define a spot object resource from an lpp_source nim object.
      ibm.power_aix.nim_resource:
        action: present
        name: "{{ spot_name_v }}"
        object_type: spot
        attributes:
          source: "{{ lpp_source_v }}"
          location: "{{ spot_final_location_v }}"
      register: result
    - debug: var=result

    - name: Show a NIM resource object.
      ibm.power_aix.nim_resource:
        action: show
        name: "{{ spot_name_v }}"
      register: result
    - debug: var=result

    - name: Verify the resource is exist.
      assert:
        that:
          - "{{ result.nim_resource_found }}"
        fail_msg: "The member {{ spot_name_v }} was not found"

    - name: Try to show a NIM resource object that does not exist.
            (do not return an error)
      ibm.power_aix.nim_resource:
        action: show
        name: i_dont_exist
      register: result
    - debug: var=result

    - name: Show/display all the NIM spot resource objects.
      ibm.power_aix.nim_resource:
        action: show
        object_type: spot
      register: result
    - debug: var=result

    - name: Show only the type lpp_source NIM resource objects.
      ibm.power_aix.nim_resource:
        action: show
        object_type: lpp_source
      register: result
    - debug: var=result

    - name: Verify the resource is exist.
      assert:
        that:
          - "{{ result.nim_resource_found }}"
        fail_msg: "Problem: No lpp_source object types found."

    - name: Remove a NIM spot object resource.
      ibm.power_aix.nim_resource:
        action: absent
        name: "{{ spot_name_v }}"
      register: result
    - debug: var=result

    - name: Verify the spot object was removed.
      ibm.power_aix.nim_resource:
        action: show
        name: "{{ spot_name_v }}"
      register: result
    - debug: var=result

    - assert:
        that:
          - result.stderr is search("0042-053")
        fail_msg: "The member {{spot_name_v }} was not removed."

    - name: Remove an object resource again (idempotency)
      ibm.power_aix.nim_resource:
        action: absent
        name: "{{ spot_name_v }}"
      register: result
    - debug: var=result

# Tests. Run expected functions with check_mode set.

    - name: Show a NIM resource object with check_mode set.
      ibm.power_aix.nim_resource:
        action: show
        name: "{{ spot_name_v }}"
      check_mode: true
      register: result
    - debug: var=result

    - name: Assert if preview mode is not shown
      assert:
        that:
          - result.msg is search("preview")
        fail_msg: "The 'show' action is not working in check mode"

    - name: Create/define an lpp_source NIM resource object from the 
            software in the system with check_mode set.
      ibm.power_aix.nim_resource:
        action: present
        name: "{{ lpp_source_v }}"
        object_type: lpp_source
        attributes:
          source: "{{ software_lpp_source }}"
          location: "{{ lpp_source_location}}"
      check_mode: true
      register: result
    - debug: var=result

    - name: Assert if preview mode is not shown
      assert:
        that:
          - result.msg is search("preview")
        fail_msg: "The 'present' action is not working in check mode"

    - name: Remove the spot resource, with check_mode set.
      ibm.power_aix.nim_resource:
        action: absent
        name: "{{ spot_name_v }}"
      check_mode: true
      register: result
    - debug: var=result

    - name: Assert if preview mode is not shown
      assert:
        that:
          - result.msg is search("preview")
        fail_msg: "The 'remove' action is not working in check mode"


#    - name: End the playbook 1
#      meta: end_host


